[package]
<<<<<<< HEAD
name = "lesson_seven"
version = "0.1.0"
authors = ["Mate <patawee@mycostech.com>"]
=======
name = "lesson_five"
version = "0.1.0"
authors = ["blittable <blittable-bits@gmail.com>"]
>>>>>>> origin/master
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
