[book]
authors = ["Mycos Technologies"]
language = "en"
multilingual = true 
src = "src"
title = "Rust Top-Down"
categories = "tutorial, training notes, oo, learning rust"

[output.html.playpen]
editable = true
