# Use Rust docker image, see: https://hub.docker.com/_/rust/
image: rust:latest

# Defines stages which are to be executed
stages:
  - build

# Run `cargo build` for the project with stable Rust
run-build:
  stage: build
  image: rust:latest
  script:
  - rustc --version && cargo --version
  - cargo build --release --jobs 1
