language: rust
branches:
  except:
  - master
rust:
  - stable
cache: cargo
before_script:
  - rustup component add rustfmt clippy
script:
  - cargo fmt --all -- --check
  - cargo clippy --all
  - cargo build
  - cargo test
