# Defines stages which are to be executed
stages:
  - build
  - package
  - run

# Run `cargo build` for the project with stable Rust
build_job:
  stage: build
  only:
    - susu-db
  before_script:
    - rustup default stable
  script:
    - rustc --version && cargo --version
    - cd project/susu
    - cargo build --release --jobs 1
  artifacts:
    expire_in: 1h
    paths: 
      - 'project/susu/target/'

package_job:
  stage: package
  only:
    - susu-db
  before_script:
    - cargo login %LOGIN_KEY%
  script:
    - cd project/susu
    - cargo publish --dry-run --allow-dirty
    - cargo publish --allow-dirty

run_job:
  stage: run
  only:
    - susu-db
  script:
    - cd project/susu
    - cargo run --release --bin susu