# Defines stages which are to be executed
stages:
  - build
  - remove
  - package
  - benchmark

build_job:
  stage: build
  only:
    - susu-db
  before_script:
    - rustup default stable
  script:
    - rustc --version && cargo --version
    - cd project/susu/src/susudb
    - cargo build --release
  artifacts:
    expire_in: 1h
    paths: 
      - 'project/susu/src/susudb/target/'

remove_job:
  stage: remove
  only:
    - susu-db
  before_script:
    - cargo login %LOGIN_KEY%
  script:
    - cd project/susu/src/susudb
    - cargo yank --vers 1.0.0
  allow_failure: true

package_job:
  stage: package
  only:
    - susu-db
  script:
    - cd project/susu/src/susudb
    - cargo publish --allow-dirty

benchmark_job:
  stage: benchmark
  only:
    - susu-db
  script:
    - cd project/susu
    - cargo bench
  artifacts:
    expire_in: 1d
    paths: 
      - 'project/susu/target/criterion/'