[package]
name = "susudb"
version = "1.0.0"
authors = ["MyCos Tech <sales@mycostech.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crc32fast = "1.2.0"

[lib]
name = "susudb"
path = "lib.rs"