[package]
name = "binary_tree_hw"
version = "0.1.0"
authors = ["Khwan"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
